### ISSUE TITLE
Multiple 'databse is locked' exceptions while opening solution in VS

### ISSUE THREAD

**Issue by CarstenL** [sboulema/TSVN#67]
After updating the plugin to the newest version (5.0.686) i get the following exceptions when starting my solution.

![image](https://user-images.githubusercontent.com/5153891/124708440-98b32680-defa-11eb-9f41-eb9c8e80e18a.png)

![image](https://user-images.githubusercontent.com/5153891/124708461-9d77da80-defa-11eb-9b0c-12995e2092cb.png)

Based on the size of my solution, i get the above messages between 5 and 300 times.

According to TortoiseSVN there are no locks on the paths.
Cleanup and other "solutions" didnt work.

Commit, Update etc. works fine with TortoiseSVN and the plugin (after closing the error messages), but it is quite annoying when you have to wait for 300 errors ;-)

Not every of my solutions is affected.
It almost seems that only those are affected where a .NET web site project is included.

VisualStudio 2019 16.10.3
TortoiseSVN 1.14.1.29085
TSVN Plugin 5.0.686

**Comment by sboulema** [comment]
Did you try this solution: https://stackoverflow.com/a/11764922/2235860

> Go to top level SVN folder.
Right click on folder (that has your svn files) > TortoiseSVN > CleanUp
Note. Make sure "Break locks" option is selected in the Cleanup dialog.

Will try to reproduce on my machine with a web site project

**Comment by CarstenL** [comment]
> Did you try this solution: https://stackoverflow.com/a/11764922/2235860
> 
> > Go to top level SVN folder.
> > Right click on folder (that has your svn files) > TortoiseSVN > CleanUp
> > Note. Make sure "Break locks" option is selected in the Cleanup dialog.
> 
> Will try to reproduce on my machine with a web site project

yes cleanup multiple times with Break locks option and on different folder levels but nothing helps

**Comment by m-gallesio** [comment]
Something like this is happening to us as well, but only when the solution is compiled and not when it is started.

We are building a project which uses gulp to transpile TypeScript files, using Node.js.
This creates a new directory with the compiled files every time compilation is triggered.
This directory is in the svn:ignore list since it does not need to be versioned.

Upon compilation, a very large number of error messages starts popping up.
Some more examples in additional to the ones listed above:
* [directory] is not a working copy.
* Failed to lock working copy [directory]. sqlite[S5]: database is locked.
* sqlite[S5]: database is locked. Another process is blocking the working copy database [...]
* Working copy [directory] locked. [directory] is already locked. Please execute the 'Cleanup' command.

The only way to stop this seems to be forcefully close Visual Studio.

Afterwards:
* the output directory (or at least part of it) is marked as "added" by SVN, even if it is in the ignore list
* some kind of write lock gets applied to the output directory

This situation can be solved by:
* removing the files and undoing the Add command
* executing the Cleanup command with the options "Clean up working copy status" and "Break write locks" enabled.

Nevertheless as long as this happens this extension is completely unusable for us.

Extension version: 5.0.707
Visual Studio version: 2019 16.10.3
TortoiseSVN version: TortoiseSVN 1.14.1, Build 29085 - 64 Bit , 2021/02/09 16:17:02

**Comment by sboulema** [comment]
Could you check if disabling the TSVN option to automatically add files, makes a difference?

**Comment by m-gallesio** [comment]
Assuming this is what you mean:
![tsvn_options](https://user-images.githubusercontent.com/46478501/124902126-f327b200-dfe2-11eb-9706-8b0fd3201677.png)
All of the boxes were already unchecked before.

**Comment by sboulema** [comment]
Problem found, working on a fix!

**Comment by sboulema** [comment]
Should be fixed in the new release 🚀 
Be sure to get the right version because I have splitted the extension in a VS2022 version and a VS2019 and prior version.

Will be on holiday from tomorrow, so new builds will have to wait for a bit 🌞

**Comment by m-gallesio** [comment]
It indeed seems to be fixed, at the very least in our specific use case. Thank you for your swift response.

**Comment by CarstenL** [comment]
My error messages are also gone now when starting the solution.
Thanks!
